#!/usr/bin/env bash

set -xe
apt-get update -q
apt-get install -y apt-transport-https lsb-release ca-certificates

# Add basic repository
echo "deb https://packages.sury.org/php/ jessie main" >> /etc/apt/sources.list
echo "deb-src https://packages.sury.org/php/ jessie main" >> /etc/apt/sources.list
wget -O- "https://packages.sury.org/php/apt.gpg" | apt-key add -
apt-get update -q
apt-get upgrade -y
