#!/usr/bin/env bash

set -xe

# Install PHP 7 and its modules
apt-get install -y \
    php7.0 \
    php7.0-bz2 \
    php7.0-curl \
    php7.0-gd \
    php7.0-imagick \
    php7.0-json \
    php7.0-mbstring \
    php7.0-mcrypt \
    php7.0-mysql \
    php7.0-sqlite3 \
    php7.0-xml \
    php7.0-zip \
    php7.0-xdebug
