#!/usr/bin/env bash

set -xe

# Install PHP 7 and its modules
apt-get install -y \
    php7.1 \
    php7.1-bz2 \
    php7.1-curl \
    php7.1-gd \
    php7.1-imagick \
    php7.1-json \
    php7.1-mbstring \
    php7.1-mcrypt \
    php7.1-mysql \
    php7.1-sqlite3 \
    php7.1-xml \
    php7.1-zip \
    php7.1-xdebug
