#!/usr/bin/env bash

set -xe

# Install Google Chrome
curl -sS -L https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
apt-get update -q
apt-get install -y google-chrome-stable

rm /etc/apt/sources.list.d/google.list
sh /scripts/cleanup
