#!/usr/bin/env bash

set -xe

# Install PHP 5 and its modules
apt-get install -y \
    php5 \
    php5-curl \
    php5-gd \
    php5-imagick \
    php5-json \
    php5-mcrypt \
    php5-mysql \
    php5-sqlite \
    php5-xdebug
