#!/usr/bin/env bash

set -xe

# Add sury repository
echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list
echo "deb-src https://packages.sury.org/php/ jessie main" >> /etc/apt/sources.list.d/php.list
wget -O- "https://packages.sury.org/php/apt.gpg" | apt-key add -

# Install PHP 7 and its modules
apt-get update -q
apt-get install -y \
    php7.2-fpm \
    php7.2-bz2 \
    php7.2-curl \
    php7.2-gd \
    php7.2-imagick \
    php7.2-json \
    php7.2-mbstring \
    php7.2-mysql \
    php7.2-sqlite3 \
    php7.2-xml \
    php7.2-zip \
    php7.2-xdebug

rm /etc/apt/sources.list.d/php.list
sh /scripts/cleanup
